# Generated by Django 5.2.8 on 2025-11-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Cat",
            new_name="Car",
        ),
    ]
